-- CreateEnum
ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'CUSTOMER';

-- AlterTable
ALTER TABLE "Request" ADD COLUMN "userId" TEXT;

-- AddForeignKey
ALTER TABLE "Request"
ADD CONSTRAINT "Request_userId_fkey"
FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
